#pragma once

#include <juce_dsp/juce_dsp.h>

// One stage of Tenebrae's waveshaper cascade: gain -> asymmetric tanh
// nonlinearity -> a fixed interstage high/low shaping filter pair.
//
// The interstage filter is deliberately NOT user-automatable - it exists so
// that two or three cascaded clippers driven at the same input level don't
// just pile up into an ever-fizzier, ever-boomier mess. Each stage in
// TenebraeEngine is constructed with its own fixed (asymmetry, highPassHz,
// lowPassHz) triple that tightens the low end and trims a bit more top-end
// fizz than the last, so the cascade progressively focuses onto the "chug"
// band rather than amplifying whatever the previous stage left unfiltered.
//
// Runs entirely inside the oversampled block (see TenebraeEngine::process),
// so both the nonlinearity and the interstage filtering happen at N times
// the host sample rate - keeping aliasing generated by every stage, not just
// the first, out of the audible band.
//
// Allocation-free after prepare(); safe to call setDriveDb()/process() from
// the audio thread.
class CascadeStage
{
public:
    CascadeStage (float asymmetry, float highPassFrequencyHz, float lowPassFrequencyHz);

    // `spec` must describe the OVERSAMPLED rate/block size (host rate and
    // block size multiplied by the oversampling factor), since this stage
    // runs entirely inside the oversampled block.
    void prepare (const juce::dsp::ProcessSpec& spec);

    void reset();

    // Processes `context` in place, at the oversampled rate.
    void process (juce::dsp::ProcessContextReplacing<float>& context);

    // Gain into this stage's nonlinearity, in dB. Fixed per-stage cascade
    // voicing (see TenebraeEngine.cpp) rather than a user parameter, but
    // ramped via the internal juce::dsp::Gain smoother regardless - safe to
    // call every block from the audio thread.
    void setDriveDb (float newDriveDb);

private:
    static constexpr double smoothingTimeSeconds = 0.05;
    // Butterworth (maximally-flat) Q for both interstage filters.
    static constexpr float filterQ = juce::MathConstants<float>::sqrt2 / 2.0f;

    const float asymmetry;
    const float highPassFrequencyHz;
    const float lowPassFrequencyHz;

    double oversampledSampleRate = 44100.0;

    juce::dsp::Gain<float> driveGain;
    juce::dsp::ProcessorDuplicator<juce::dsp::IIR::Filter<float>, juce::dsp::IIR::Coefficients<float>> interstageHighPass;
    juce::dsp::ProcessorDuplicator<juce::dsp::IIR::Filter<float>, juce::dsp::IIR::Coefficients<float>> interstageLowPass;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (CascadeStage)
};
